-- -----------------------------------------------------------------------------
-- V2__create_income_categories_table.sql
-- -----------------------------------------------------------------------------

CREATE TABLE income_categories (
    id          BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100)    NOT NULL,
    description VARCHAR(255),
    is_active   BOOLEAN         NOT NULL DEFAULT TRUE
);
