-- -----------------------------------------------------------------------------
-- V4__create_budgets_table.sql
-- -----------------------------------------------------------------------------

CREATE TABLE budgets (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_category_id BIGINT          NOT NULL,
    amount              NUMERIC(19, 2)  NOT NULL,
    initial_date        DATE            NOT NULL,
    final_date          DATE            NOT NULL,
    state               VARCHAR(20)     NOT NULL DEFAULT 'NOT_STARTED',
    is_active           BOOLEAN         NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_budgets_expense_category
        FOREIGN KEY (expense_category_id)
        REFERENCES expense_categories (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_budgets_state
        CHECK (state IN ('WITHIN', 'NEAR_LIMIT', 'FULLY_USED', 'OVER', 'NOT_STARTED'))
);
