-- V5__create_expenses_table.sql

CREATE TABLE expenses (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expense_category_id BIGINT          NOT NULL,
    account_id          BIGINT          NOT NULL,
    amount              NUMERIC(19, 2)  NOT NULL,
    date                DATE            NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT fk_expenses_expense_category
        FOREIGN KEY (expense_category_id)
        REFERENCES expense_categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_expenses_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(id)
        ON DELETE RESTRICT
);
