-- V6__create_incomes_table.sql

CREATE TABLE incomes (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    income_category_id  BIGINT          NOT NULL,
    account_id          BIGINT          NOT NULL,
    amount              NUMERIC(19, 2)  NOT NULL,
    date                DATE            NOT NULL,
    description         VARCHAR(255),
    CONSTRAINT fk_incomes_income_category
        FOREIGN KEY (income_category_id)
        REFERENCES income_categories(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_incomes_account
        FOREIGN KEY (account_id)
        REFERENCES accounts(id)
        ON DELETE RESTRICT
);
