-- -----------------------------------------------------------------------------
-- V7__create_transfers_table.sql
-- -----------------------------------------------------------------------------

CREATE TABLE transfers (
    id                  BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_account_id   BIGINT          NOT NULL,
    target_account_id   BIGINT          NOT NULL,
    amount              NUMERIC(19, 2)  NOT NULL,
    date                DATE            NOT NULL,

    CONSTRAINT fk_transfers_source_account
        FOREIGN KEY (source_account_id)
        REFERENCES accounts (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_transfers_target_account
        FOREIGN KEY (target_account_id)
        REFERENCES accounts (id)
        ON DELETE RESTRICT,
    CONSTRAINT chk_transfers_different_accounts
        CHECK (source_account_id <> target_account_id)
);

CREATE INDEX idx_transfers_source_account
    ON transfers (source_account_id);

CREATE INDEX idx_transfers_target_account
    ON transfers (target_account_id);
